name: Exercise 10
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  compress_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compress
        run: "tar czf src.tar.gz ./src"
      - name: Commit
        run: |
          git add src.tar.gz
          git config --local user.email "rafael.monzo-bravo@capgemini.com"
          git config --local user.name "rafamonzb"
          git commit -m "Add or renew artifact"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: rafamonzb/artifactManagement
          branch: main
