name: Exercise 10
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  compress_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compress
        run: "tar czf src.tar.gz ./src"
      - name: Push to secondary repo
        run: |
          git config --unset-all http.https://github.com/.extraheader

          git clone https://rafamonzb:$GITHUB_TOKEN@github.com/rafamonzb/artifactManagement.git

          mv src.tar.gz ./artifactManagement/src.tar.gz
          cd artifactManagement

          git remote -v

          git add .
          git commit -m "Add or renew artifact"

          git push --set-upstream origin main