name: Exercise 10
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  compress_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout artifact repo
        uses: actions/checkout@v4
        with:
          repository: rafamonzb/artifactManagement
          token: ${{ secrets.PAT_TOKEN}}
          path: artifact

      - name: Compress
        run: "tar czf ./artifact/src.tar.gz ./mainrepo/src"
        
      - name: Push to artifact repo
        env:
          COMMIT_MESSAGE: Create or update artifact file
          COMMIT_AUTHOR: github-actions[bot]
          COMMIT_EMAIL: username@users.noreply.github.com
        run: |
          cd artifact

          git config --global user.email "${{ env.COMMIT_EMAIL }}"
          git config --global user.name "${{ env.COMMIT_AUTHOR }}"

          git add .
          git commit -m "${{ env.COMMIT_MESSAGE }}"

          git push