name: Exercise 11
on:
  push:
  pull_request:
jobs:
  coverage_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Download dependencies
        run: npm ci

      - name: Test with coverage
        run: npx jest --coverage --coverageReporters=text --coverageReporters=cobertura

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/cobertura-coverage.xml
        
      - name: Add summary
        id: coverage
        run: |
          PERCENTAGE=$(grep -o 'line-rate="[0-9.]*"' coverage/cobertura-coverage.xml | head -1 | sed 's/[^0-9.]//g')
          COVERAGE=$(awk "BEGIN {print int($PERCENTAGE * 100)}")
          echo "CODE COVERAGE: **${COVERAGE}%**" >> $GITHUB_STEP_SUMMARY