name: Exercise 06
on:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cleanup
        uses: digicert/prune_old_branches_action@v9
        with:
          numDays: '180'
          numTags: '3'
